// Generates src/elements/_icons.js from the PRODUCT icon library (src/assets/icons/icons.js) —
// the SAME set shown on the Assets → Icons page. There is ONE icon library (the product's); obs-icon
// draws its glyphs from it. Never hand-edit _icons.js — add/update icons in src/assets/icons/icons.js
// and re-run this (it runs automatically before `build` and `site:build`).
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { productRoot } from './lib/product-root.mjs'

const HERE = path.dirname(fileURLToPath(import.meta.url))
const LIB = path.resolve(HERE, '..')
const ROOT = productRoot()
if (!ROOT) {
  console.error('✗ product checkout not found — set OBSERVEOPS_ROOT or clone ObserveOps at ../PROJECT/ObserveOps')
  process.exit(1)
}
const SRC = path.join(ROOT, 'src', 'assets', 'icons', 'icons.js')
const OUT = path.resolve(LIB, 'src', 'elements', '_icons.js')

// obs-* shorthand names that map to a differently-named product icon (kept working, not a second library).
// NOTE (G3): the product's `unlockAlt` glyph actually DRAWS an undo / counter-clockwise arrow, NOT an open lock.
// Expose it under the names that match what it draws so callers stop shipping a "lock" that's really an undo arrow.
const ALIASES = { calendar: 'calendarAlt', undo: 'unlockAlt', rotateLeft: 'unlockAlt', unlock: 'lockOpen', lockAltOpen: 'lockOpen', lockOpenAlt: 'lockOpen' }

// DS-LOCAL glyph additions NOT in the product library yet (G3). Authored in the product's 48×48 solid style to match
// lockAlt (verified by rendering), so a public/private lock pair is consistent: lockAlt (closed) + lockOpen (open).
// even-odd: solid body with a punched keyhole + an open shackle whose right leg is lifted.
const EXTRA = {
  lockOpen: { w: 48, h: 48, p: 'M10,20 h28 a4,4 0 0 1 4,4 v14 a4,4 0 0 1 -4,4 h-28 a4,4 0 0 1 -4,-4 v-14 a4,4 0 0 1 4,-4 z M24,26.4 a2.3,2.3 0 1 0 0.01,0 z M22.8,29 h2.4 l-0.6,5.4 h-1.2 z M14,20 v-4 a8,8 0 0 1 15.5,-2.6 l-2.8,0.9 a5,5 0 0 0 -9.7,1.7 v4 z' },
}

const toCamel = (s) => s.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase())

function loadProductIcons() {
  const cjs = fs.readFileSync(SRC, 'utf8').replace(/export\s+const\s+/g, 'exports.')
  const mod = {}
  // eslint-disable-next-line no-new-func
  new Function('exports', cjs)(mod)
  const out = {}
  const kebab = {} // camelKey → original kebab iconName (kept verbatim; camel→kebab round-trip is lossy for digits)
  let dupes = 0
  for (const v of Object.values(mod)) {
    if (!v || !Array.isArray(v.icon) || !v.iconName) continue
    const [w, h, , , pathData] = v.icon
    const d = Array.isArray(pathData) ? pathData[pathData.length - 1] : pathData
    if (!d) continue
    const key = toCamel(v.iconName)
    if (out[key]) dupes++
    out[key] = { w, h, p: d }
    kebab[key] = v.iconName
  }
  if (dupes) console.warn(`  ⚠ ${dupes} duplicate iconName(s) in product icons.js — last one won`)
  return { map: out, kebab }
}
// camelCase key → kebab name (safe for the DS-local EXTRA/ALIAS keys, which have no digit-after-hyphen edge cases)
const toKebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase()

const { map: icons, kebab: kebabName } = loadProductIcons()
for (const [k, v] of Object.entries(EXTRA)) if (!icons[k]) { icons[k] = v; kebabName[k] = toKebab(k) } // DS-local additions
for (const [alias, target] of Object.entries(ALIASES)) {
  if (icons[target] && !icons[alias]) { icons[alias] = icons[target]; kebabName[alias] = toKebab(alias) }
}

// icons whose single path relies on the even-odd fill rule (holes/half-fills) — obs-icon applies fr per-icon
const EVENODD = new Set(['themeAuto', 'lockOpen', 'unlock', 'lockAltOpen', 'lockOpenAlt', 'customReport'])

// UNION SAFETY (drift fix): preserve any icon already in the committed _icons.js that THIS product checkout happens
// to lack — so regenerating from a different/older product never DROPS an icon other components rely on (a contributor
// building from a newer product branch, or DS-local additions). Additive-only; it never removes. If you intend to
// remove an icon, delete its line from _icons.js AND from the product in the same change.
if (fs.existsSync(OUT)) {
  const prev = fs.readFileSync(OUT, 'utf8')
  const RE = /^\s*([A-Za-z0-9_]+):\s*\{\s*w:\s*(\d+),\s*h:\s*(\d+),\s*p:\s*'([^']*)'(?:,\s*fr:\s*'([^']*)')?\s*\},?\s*$/gm
  let m, kept = 0
  while ((m = RE.exec(prev))) {
    if (m[1] in icons) continue
    icons[m[1]] = { w: +m[2], h: +m[3], p: m[4] }
    kebabName[m[1]] = toKebab(m[1])
    if (m[5] === 'evenodd') EVENODD.add(m[1])
    kept++
  }
  if (kept) console.warn(`  ⚠ union: kept ${kept} committed icon(s) this product checkout lacks (drift-safe; not dropped)`)
}

const keys = Object.keys(icons).sort((a, b) => a.localeCompare(b))
const body = keys
  .map((k) => `  ${k}: { w: ${icons[k].w}, h: ${icons[k].h}, p: '${icons[k].p}'${EVENODD.has(k) ? ", fr: 'evenodd'" : ''} },`)
  .join('\n')

const header = `// GENERATED by scripts/build-icons.mjs — DO NOT EDIT BY HAND.
// Source of truth: src/assets/icons/icons.js (the product Font Awesome Light library, shown on the Assets → Icons page).
// To add/change an icon: edit the product icons.js, then run \`npm run icons:build\` (runs automatically before build).
// obs-icon resolves both camelCase ('chevronDoubleLeft') and kebab ('chevron-double-left') names. ${keys.length} icons.
`

fs.writeFileSync(OUT, `${header}export const ICONS = {\n${body}\n}\n`)
console.log(`✓ _icons.js ← ${keys.length} icons from product library`)

// name manifest → components/registry/icon.json `names` (names only, for AI discoverability — parallels logo.json,
// so an AI can list/resolve real icon names via the MCP instead of concluding an icon is "missing" + hand-drawing one).
// `list` = the kebab names callers type (obs-icon also accepts camelCase); `aliases` maps DS shorthands → canonical.
const REG = path.resolve(LIB, '..', 'components', 'registry', 'icon.json')
if (fs.existsSync(REG)) {
  const aliasKebab = {}
  for (const [alias, target] of Object.entries(ALIASES)) aliasKebab[toKebab(alias)] = toKebab(target)
  const list = [...new Set(keys.map((k) => kebabName[k] || toKebab(k)))].sort((a, b) => a.localeCompare(b))
  const reg = JSON.parse(fs.readFileSync(REG, 'utf8'))
  reg.names = { total: list.length, list, aliases: aliasKebab, evenodd: [...EVENODD].map(toKebab).sort() }
  fs.writeFileSync(REG, `${JSON.stringify(reg, null, 2)}\n`)
  console.log(`  registry/icon.json names: ${list.length} icons (${Object.keys(aliasKebab).length} aliases)`)
}
